/* THIS FILE IS GENERATED DO NOT EDIT */
#ifndef LIMBOAI_VERSION_GEN_H
#define LIMBOAI_VERSION_GEN_H

#define LIMBOAI_VERSION_MAJOR 1
#define LIMBOAI_VERSION_MINOR 4
#define LIMBOAI_VERSION_PATCH 1
#define LIMBOAI_VERSION_STATUS ""

#define LIMBOAI_VERSION_HASH "d13e82a0f49ba96c2edbcdf0832a1781bac459a0"
#define LIMBOAI_VERSION_SHORT_HASH "d13e82a"

#define LIMBOAI_VERSION_DOC_BRANCH "v1.4.1"
#define LIMBOAI_VERSION_DOC_URL "https://limboai.readthedocs.io/en/" LIMBOAI_VERSION_DOC_BRANCH "/"

#endif // LIMBOAI_VERSION_GEN_H
