/* THIS FILE IS GENERATED DO NOT EDIT */
#ifndef LIMBOAI_VERSION_GEN_H
#define LIMBOAI_VERSION_GEN_H

#define LIMBOAI_VERSION_MAJOR 1
#define LIMBOAI_VERSION_MINOR 4
#define LIMBOAI_VERSION_PATCH 1
#define LIMBOAI_VERSION_STATUS ""

#define LIMBOAI_VERSION_HASH "3fce01a548e3d87c7cef758175b78e6c9d19e42e"
#define LIMBOAI_VERSION_SHORT_HASH "3fce01a"

#define LIMBOAI_VERSION_DOC_BRANCH "v1.4.1"
#define LIMBOAI_VERSION_DOC_URL "https://limboai.readthedocs.io/en/" LIMBOAI_VERSION_DOC_BRANCH "/"

#endif // LIMBOAI_VERSION_GEN_H
